FROM python:3.13-slim
ENV PYTHONPYCACHEPREFIX=/tmp/pycache

RUN pip install --no-cache-dir uv

WORKDIR /app

COPY pyproject.toml ./
RUN uv sync --no-install-project

COPY . .
RUN uv sync

EXPOSE 8000

CMD ["uv", "run", "uvicorn", "private_rag_apps.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
