name: Link Check

on:
  pull_request:
    paths:
      - '**/*.md'
  push:
    branches:
      - main
    paths:
      - '**/*.md'

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --no-progress
            --include-fragments
            --exclude 'localhost'
            README.md
            docs/**/*.md
          fail: true
